/var/lib/xianyu-saas/tenants/*/bot.log /var/lib/xianyu-saas/tenants/*/accounts/*/bot.log {
    su xianyu-saas xianyu-saas
    daily
    size 10M
    rotate 14
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
}
