# -*- coding: utf-8 -*-
"""完整使用教程文本：付款后发送 / 买家索要时发送"""

TUTORIAL_TEXT = (
    "DeepSeek V4 Flash / Pro API 使用教程（新用户）\n\n"
    "第一步：注册登录\n"
    "打开 https://deepwhale.chat/sub2api/ → 点右上角注册，邮箱+密码即可，不用邀请码（注册本身不赠余额，试用码需在闲鱼会话领取）\n\n"
    "第二步：兑换余额（拍下付款的）\n"
    "登录后找\"兑换码\"入口 → 输入我发你的兑换码 → 5 元到账\n\n"
    "第三步：创建密钥\n"
    "左侧\"我的密钥\" → 创建密钥 → 名称随便填，分组选 DeepSeek → 创建后复制 sk- 开头的 key\n\n"
    "第四步：接入使用\n"
    "在工具/代码里填三个东西：\n"
    "· API 地址（base_url）：https://deepwhale.chat/sub2api/v1\n"
    "· API Key：你复制的 sk-xxx\n"
    "· 模型名（二选一）：\n"
    "  - Flash 官方价格 3 折：deepseek-v4-flash\n"
    "  - Pro 官方价格 5 折：deepseek-v4-pro\n"
    "同一个 DeepSeek key 可以使用上述任一模型，按需要切换 model 即可。\n\n"
    "计费标准（元/百万 token，以下均为实付单价）：\n"
    "· Flash 3 折：输入 0.3，输出 0.6，缓存命中 0.006\n"
    "· Pro 5 折：输入 1.5，输出 3.0，缓存命中 0.0125\n\n"
    "Python 示例：\n"
    "from openai import OpenAI\n"
    "client = OpenAI(base_url=\"https://deepwhale.chat/sub2api/v1\", api_key=\"sk-你的key\")\n"
    "model = \"deepseek-v4-pro\"  # 也可改为 deepseek-v4-flash\n"
    "resp = client.chat.completions.create(model=model, messages=[{\"role\":\"user\",\"content\":\"你好\"}])\n"
    "print(resp.choices[0].message.content)\n\n"
    "查余额/用量：登录后台左侧\"用量明细\"\n\n"
    "常见报错：\n"
    "· 401 = key 填错了，检查有没有复制全/多余空格\n"
    "· 402/余额不足 = 余额用完了，拍档位续费\n"
    "· 404 = 模型名写错，确认是 deepseek-v4-flash 或 deepseek-v4-pro\n"
    "· DeepSeek 偶发网络异常、超时或卡顿 = 上游短时波动，稍后重试 1-2 次；持续失败再把报错原文发到闲鱼会话\n\n"
    "有问题随时找我～"
)
